### ISSUE TITLE
Repeatitive use of identical try...except blocks in Sol.py

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/schedula#10]
A minor comment on this lib's central piece of functionality, where user functiins are executed:

https://github.com/vinci1it2000/schedula/blob/86ebce3366bb746430805ad14f8a94d75383db21/schedula/utils/sol.py#L570-L630

There are 3 `try..except` blocks in function `_set_data_node_output()` that do the same thing.  They can be substituted with a single one with nested a little "outer" - is there any rewson not to do that?

**Comment by vinci1it2000** [comment]
This has been solved in 6d74943.
