### ISSUE TITLE
importing `schedula` imports every module there is

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/schedula#11]
The way it is structure this project, when importing `schedula.__init__.py`, it imports recursively all modules beneath them. In modern computers this is fast, but in general it should be possible to selectively import what is needed.

**Comment by vinci1it2000** [comment]
For python 3.7 schedula uses `__getattr__` to import module attributes. 
While for older python versions it imports all attributes but it takes max 12 ms.
