### ISSUE TITLE
Remove nose from `setup_requires`

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/schedula#14]
The `setup-requieres` keyword ni `setup.py` is rarely needed, if ever now that `project.toml` PEP518 is out.
Additionally, any package added there can have consequences for downstream projects & tools (e.g. it breaks conda packaging with recent conda-4.10).
Besides, `nose` is a testing library and should definetely not be there.

**Comment by vinci1it2000** [comment]
fixed with 5995d9db
