### ISSUE TITLE
Split `schedula` into 2 or more packages, with the one with the very barebone serial small implementation

### ISSUE THREAD

**Issue by KOLANICH** [vinci1it2000/schedula#19]
**Is your feature request related to a problem? Please describe.**

Sometimes when building thin abstraction layers for data conversion libraries one needs an impl like `schedula` that will determine a path in the form of chain of calls (i.e. `rst -> HTML -> MarkDown -> ANSI-highlighted MarkDown`) between backends. It looks like the thing `schedula` was made for. But one needs one's library be small. In some cases the integrators of the lib may want to vendor the dependencies, that means not only the lib itself must be as small as possible, but alsomits deps like `schedula`.

**Describe the solution you'd like**
1. `schedula` is separated into `schedula` with bells and whistles, `schedula-concurrent` with everything parallel and async and `schedula_core` doing the essential functionality, without any concurrency and other bells and whistles. It also may make sense to reuse third-party small and minimal, packages for Dijkstra algorythm.
2. each package is put into anmown git repo to minimize download size (`GitHub` doesn't support partial fetches).

**Describe alternatives you've considered**
Not using `schedula`.

**Comment by vinci1it2000** [comment]
The project is already configured to have a smaller size for running on microcontrollers by dropping some functionalities, i.e. `drw`, `io`, `ext`, `des`, and `web`.

I published the minimum version of [schedula-core](https://pypi.org/project/schedula-core/). Now the size is 70kb from full version of 2.5 MB.

**Comment by KOLANICH** [comment]
Thank you.
