### ISSUE TITLE
Pre releases do not work with readthedocs

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/schedula#2]
Still co2mpas builds fail on readthedocs because it cannot find --pre released of schedula, and picks the old one.

In general when the project is a library, it makes much sense to release more often full release.
And more so when it is at the early stages of development (as it is now).

**Comment by ankostis** [comment]
Additionally, you released `v0.1.0dev1` AFTER `v0.1.0`, which also does not make sense.
I'm surprised that pypi let you upload an earlier version...

Anyway, just release 0.1.1.

**Comment by vinci1it2000** [comment]
I have released the version v0.1.1. Now [co2mpas readthedocs](https://readthedocs.org/projects/co2mpas/) passes.
