### ISSUE TITLE
Jinja templates should use autoescape=True to reduce risk of template injection

### ISSUE THREAD

**Issue by scottgifford** [vinci1it2000/schedula#21]
**Is your feature request related to a problem? Please describe.**
The Jinja templates used for autosummary and drw currently leave the `autoescape` setting at its default value, `False`.  As a result, template variables can inject HTML into generated pages, creating a security risk if those variables are under the control of an attacker.

**Describe the solution you'd like**
Set `autoescape=True` when using Jinja

**Describe alternatives you've considered**
Update the documentation to make it clear that template values must not be under the control of an attacker

**Additional context**
This issue was found by an automated security scanner

**Comment by scottgifford** [comment]
I will provide a suggested fix in a PR shortly

**Comment by scottgifford** [comment]
Proposed fix in https://github.com/vinci1it2000/schedula/pull/22

**Comment by vinci1it2000** [comment]
Included in dev.
