### ISSUE TITLE
Get one liner formula from graph node 

### ISSUE THREAD

**Issue by dberardo-com** [vinci1it2000/schedula#25]
It would be useful to get a one liner string representing a DAG from the dispatcher.

so basically having one call like "dsp.get_one_liner(origin = 'A2')" which basically returns all subnodes of the graph starting from A2. Example:

```
A2: "=SUM(A1,A3)"
A3: "=SUM(1,3)"
A1: "=A4"
A4: "=SUM(1,1,1,1,1)"

dsp.get_one_liner(origin = 'A2') --> returns: "=SUM(SUM(1,1,1,1,1),SUM(1,3)"
dsp.get_one_liner(origin = 'A1') --> returns: "=SUM(1,1,1,1,1)"
```

and so on...

**Comment by dberardo-com** [comment]
duplicate of https://github.com/vinci1it2000/formulas/issues/119

**Comment by vinci1it2000** [comment]
Answered in https://github.com/vinci1it2000/formulas/issues/119#issuecomment-1807876350
