### ISSUE TITLE
DRY when adding sub-dispatch nodes

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/schedula#4]
When adding a subdispatch-node with `add_dispatcher()` currently you have to specify IO mappings even for names that are identical.  

I would add 2 new kwds in that method, `inp_names` & `out_names`, that accept lists of data-names that are assumed to have 1-to-1 mappings.

**Comment by vinci1it2000** [comment]
I prefer to play with the object type then add two extra kw... 

example:

    inputs=('a', 'b') 

is equivalent to 

    inputs={'a':'a','b':'b'}

**Comment by ankostis** [comment]
And can you combine both?

**Comment by vinci1it2000** [comment]
what do you mean?

**Comment by ankostis** [comment]
Specify both auto-mapped names and explicitly mapped ones, in the same `add_dispatcher()` invocation?

**Comment by vinci1it2000** [comment]
I want to avoid extra kws. I can build an utility like:

    def auto_dict(*args, **kw):
        return sh.combine_dict(kw, base={k: k for k in args}) 

what do you think?

**Comment by ankostis** [comment]
In practical terms, what you suggest achieves the same, but with more code/dependencies.

What's the reason not to add new kwds?

**Comment by vinci1it2000** [comment]
I have to add for both `inputs` and `outputs` kw, while the utl is solving both (so less code).

**Comment by ankostis** [comment]
Well, that's a valid reason.

Let's compare the two:

```python
from utils import auto_dict

add_dispatcher(
               dsp, 
               auto_dict('a', 'b', c='c_renamed'), 
               auto_dict('out_a', 'out_b', out_c='out_c_renamed'))
```
vs
```python
add_dispatcher(
               dsp, 
               {'b': 'out_b_renamed'}, 
               {'out_b': 'out_b_renamed'}, 
               inp_names=['a', 'b'], 
               out_names=['a_out', 'b_out']))
```

I like the use of python's kwd syntax.
Note though that most of the time, at least in co2mpas code, it would be only the last 2 kwds that are used - no that many renamed params.

But with an intermediate function you loose the opportunity to invoke sub-dispatchers directly from configuration text-files, at least not without requiring the use of that helper function, in which case, why not add the kwds anyway?

In any case, `auto_dict` is totally opaque name to tell what it does, and hard to remember with all other auto-magic dict functions.
I would call it `identical_kv_dict` or even shorter `idkvmap`.

**Comment by ankostis** [comment]
Of course the optimal would be, since most of the times only the identical kvs are used, add a new method that has the `inp_names`/`out_names` kwds as the first args of the new methods, and move [`inputs`/`outputs`](https://github.com/vinci1it2000/schedula/blob/3e667fcf2ca4cb1b2818b38d0f5ba49e679bc4f5/schedula/dispatcher.py#L554) args at the end.
So in a nutshell, reverse the meaning of those two.

That's refactoring for DRY.

**Comment by ankostis** [comment]
Something like this?

```python
add_dispatcher(
               dsp, 
               ['a', 'b', {'c'='c_renamed'}], 
               ('out_a', 'out_b', dict(out_c='out_c_renamed'))
```

And these should be invalid:
```python
add_dispatcher(
               dsp, 
               'abc',  # valid: a sequence 
               ('out_a', 'out_b', dict(out_c='out_c_renamed'), 'd')  # INVALID: trailing element
```

**Comment by vinci1it2000** [comment]
Implementation example:

    d.add_dispatcher(dsp, inputs=('a', {'b': 'c'}, 'd', {'e': 'f', 'g': 'h'})
equivalent:

    d.add_dispatcher(dsp, inputs={'a': 'a', 'b': 'c', 'd': 'd', 'e': 'f', 'g': 'h'})
