### ISSUE TITLE
No wheel released in PyPi repo

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/schedula#6]
Currently no wheel has been published in [PyPi repo](https://pypi.python.org/pypi/schedula) - only sources.

The way to reolve this is to use these 2 commands on the next release:

```bash
python setup.py sdist bdist_wheel ## Build sources and whl into ./dist/ dir
twine upload dist/*                ## Release built wheel
```

**Comment by vinci1it2000** [comment]
Done. https://pypi.python.org/pypi/schedula/0.1.11
